/** 小组赛全部结束后锁定的 32 强对阵（2026.06.27） */
export interface RoundOf32FinalMatch {
  matchNo: number;
  date: string;
  time: string;
  venue: string;
  city: string;
  home: string;
  away: string;
  qualLabel: string;
  played: boolean;
  /** 常规时间比分（主队视角） */
  score?: string;
  /** 点球 / 加时等补充说明 */
  scoreNote?: string;
  winner?: string;
}

export const ROUND_OF_32_FINAL: RoundOf32FinalMatch[] = [
  {
    matchNo: 73,
    date: '06-28',
    time: '12:00 PT',
    venue: 'SoFi 球场',
    city: '英格尔伍德',
    home: '南非',
    away: '加拿大',
    qualLabel: 'A 组第二 · B 组第二',
    played: true,
    score: '0-1',
    winner: '加拿大',
  },
  {
    matchNo: 74,
    date: '06-29',
    time: '16:30 ET',
    venue: '吉列球场',
    city: '福克斯堡',
    home: '德国',
    away: '巴拉圭',
    qualLabel: 'E 组第一 · D 组第三 (+8)',
    played: true,
    score: '1-1',
    scoreNote: '巴拉圭 4-3 点球',
    winner: '巴拉圭',
  },
  {
    matchNo: 75,
    date: '06-29',
    time: '19:00 CT',
    venue: 'BBVA 球场',
    city: '蒙特雷',
    home: '荷兰',
    away: '摩洛哥',
    qualLabel: 'F 组第一 · C 组第二',
    played: true,
    score: '1-1',
    scoreNote: '摩洛哥 3-2 点球',
    winner: '摩洛哥',
  },
  {
    matchNo: 76,
    date: '06-29',
    time: '12:00 CT',
    venue: 'NRG 球场',
    city: '休斯顿',
    home: '巴西',
    away: '日本',
    qualLabel: 'C 组第一 · F 组第二',
    played: true,
    score: '2-1',
    winner: '巴西',
  },
  {
    matchNo: 77,
    date: '06-30',
    time: '17:00 ET',
    venue: '大都会人寿球场',
    city: '东卢瑟福',
    home: '法国',
    away: '瑞典',
    qualLabel: 'I 组第一 · F 组第三 (+8)',
    played: true,
    score: '3-0',
    winner: '法国',
  },
  {
    matchNo: 78,
    date: '06-30',
    time: '12:00 CT',
    venue: 'AT&T 球场',
    city: '阿灵顿',
    home: '科特迪瓦',
    away: '挪威',
    qualLabel: 'E 组第二 · I 组第二',
    played: true,
    score: '1-2',
    winner: '挪威',
  },
  {
    matchNo: 79,
    date: '06-30',
    time: '19:00 CT',
    venue: '阿兹特克球场',
    city: '墨西哥城',
    home: '墨西哥',
    away: '厄瓜多尔',
    qualLabel: 'A 组第一 · E 组第三 (+8)',
    played: true,
    score: '2-0',
    winner: '墨西哥',
  },
  {
    matchNo: 80,
    date: '07-01',
    time: '12:00 ET',
    venue: '梅赛德斯-奔驰球场',
    city: '亚特兰大',
    home: '英格兰',
    away: '民主刚果',
    qualLabel: 'L 组第一 · K 组第三 (+8)',
    played: true,
    score: '2-1',
    winner: '英格兰',
  },
  {
    matchNo: 81,
    date: '07-01',
    time: '17:00 PT',
    venue: "Levi's 球场",
    city: '圣克拉拉',
    home: '美国',
    away: '波黑',
    qualLabel: 'D 组第一 · B 组第三 (+8)',
    played: true,
    score: '2-0',
    winner: '美国',
  },
  {
    matchNo: 82,
    date: '07-01',
    time: '13:00 PT',
    venue: '流明球场',
    city: '西雅图',
    home: '比利时',
    away: '塞内加尔',
    qualLabel: 'G 组第一 · I 组第三 (+8)',
    played: true,
    score: '3-2',
    scoreNote: '加时',
    winner: '比利时',
  },
  {
    matchNo: 83,
    date: '07-02',
    time: '19:00 ET',
    venue: 'BMO 球场',
    city: '多伦多',
    home: '葡萄牙',
    away: '克罗地亚',
    qualLabel: 'K 组第二 · L 组第二',
    played: true,
    score: '2-1',
    winner: '葡萄牙',
  },
  {
    matchNo: 84,
    date: '07-02',
    time: '12:00 PT',
    venue: 'SoFi 球场',
    city: '英格尔伍德',
    home: '西班牙',
    away: '奥地利',
    qualLabel: 'H 组第一 · J 组第二',
    played: true,
    score: '3-0',
    winner: '西班牙',
  },
  {
    matchNo: 85,
    date: '07-02',
    time: '20:00 PT',
    venue: 'BC Place',
    city: '温哥华',
    home: '瑞士',
    away: '阿尔及利亚',
    qualLabel: 'B 组第一 · J 组第三 (+8)',
    played: true,
    score: '2-0',
    winner: '瑞士',
  },
  {
    matchNo: 86,
    date: '07-03',
    time: '18:00 ET',
    venue: '硬石球场',
    city: '迈阿密',
    home: '阿根廷',
    away: '佛得角',
    qualLabel: 'J 组第一 · H 组第二',
    played: false,
  },
  {
    matchNo: 87,
    date: '07-03',
    time: '20:30 CT',
    venue: '箭头球场',
    city: '堪萨斯城',
    home: '哥伦比亚',
    away: '加纳',
    qualLabel: 'K 组第一 · L 组第三 (+8)',
    played: false,
  },
  {
    matchNo: 88,
    date: '07-03',
    time: '14:00 CT',
    venue: 'AT&T 球场',
    city: '阿灵顿',
    home: '澳大利亚',
    away: '埃及',
    qualLabel: 'D 组第二 · G 组第二',
    played: false,
  },
];
