import type { TeamLineup } from './lineupTypes';

function L(
  formation: string,
  starters: Array<[number, string, 'GK' | 'DF' | 'MF' | 'FW']>,
  substitutes: Array<[number, string, 'GK' | 'DF' | 'MF' | 'FW']> = [],
  note?: string,
): TeamLineup {
  return {
    formation,
    starters: starters.map(([number, name, position]) => ({ number, name, position })),
    substitutes: substitutes.map(([number, name, position]) => ({ number, name, position })),
    note,
  };
}

/** 各队预测首发（综合 OPTA / 媒体赛前预测与近期用人） */
export const TEAM_LINEUPS: Record<string, TeamLineup> = {
  墨西哥: L('4-2-3-1', [
    [1, '劳尔·兰赫尔', 'GK'],
    [23, '赫苏斯·加利亚多', 'DF'],
    [5, '约翰·巴斯克斯', 'DF'],
    [15, '伊斯雷尔·雷耶斯', 'DF'],
    [3, '塞萨尔·蒙特斯', 'DF'],
    [6, '埃里克·利拉', 'MF'],
    [4, '埃德森·阿尔瓦雷斯', 'MF'],
    [25, '罗伯托·阿尔瓦拉多', 'MF'],
    [8, '阿尔瓦罗·菲达尔戈', 'MF'],
    [16, '胡利安·基尼奥内斯', 'MF'],
    [9, '劳尔·希门尼斯', 'FW'],
  ], [[11, '圣地亚哥·希门尼斯', 'FW'], [26, '布里安·古铁雷斯', 'MF'], [7, '吉尔贝托·莫拉', 'FW']], '东道主末轮或轮换'),

  韩国: L('3-4-2-1', [
    [1, '金承奎', 'GK'],
    [3, '李基赫', 'DF'],
    [4, '金玟哉', 'DF'],
    [2, '李韩范', 'DF'],
    [22, '薛英佑', 'MF'],
    [6, '黄仁范', 'MF'],
    [8, '白昇浩', 'MF'],
    [13, '李太锡', 'MF'],
    [19, '李刚仁', 'MF'],
    [10, '李在城', 'MF'],
    [7, '孙兴慜', 'FW'],
  ], [[18, '吴贤揆', 'FW'], [11, '黄喜灿', 'FW'], [15, '金纹焕', 'DF']], '末轮对南非需取胜'),

  捷克: L('4-2-3-1', [
    [1, '吉热·斯坦尼克', 'GK'],
    [5, '托马斯·霍莱什', 'DF'],
    [4, '罗宾·赫拉纳奇', 'DF'],
    [3, '大卫·兹马', 'DF'],
    [18, '大卫·尤拉塞克', 'DF'],
    [23, '米哈尔·萨迪克', 'MF'],
    [14, '卢卡斯·切尔夫', 'MF'],
    [8, '安东宁·巴拉克', 'MF'],
    [10, '帕维尔·绍切克', 'MF'],
    [9, '帕特里克·希克', 'FW'],
    [17, '亚当·赫洛热克', 'FW'],
  ], [[11, '扬·库赫塔', 'FW'], [12, '托马斯·索塞克', 'MF']]),

  南非: L('4-4-2', [
    [16, 'Ronwen Williams', 'GK'],
    [2, 'Khuliso Khumalo', 'DF'],
    [21, 'Grant Kekana', 'DF'],
    [4, 'Teboho Mokoena', 'DF'],
    [13, 'Sifiso Mnguni', 'DF'],
    [15, 'Sphephelo Sithole', 'MF'],
    [8, 'Teboho Mokoena', 'MF'],
    [11, 'Percy Tau', 'MF'],
    [10, 'Sphelele Mkhulise', 'MF'],
    [9, 'Evidence Makgopa', 'FW'],
    [17, 'Zakhele Lepasa', 'FW'],
  ], [[7, 'Lyle Foster', 'FW']]),

  加拿大: L('4-3-3', [
    [1, 'Dayne St. Clair', 'GK'],
    [2, 'Alistair Johnston', 'DF'],
    [4, 'Derek Cornelius', 'DF'],
    [5, 'Kamal Miller', 'DF'],
    [3, 'Sam Adekugbe', 'DF'],
    [7, 'Stephen Eustáquio', 'MF'],
    [6, 'Samuel Piette', 'MF'],
    [20, 'Jonathan David', 'MF'],
    [11, 'Tajon Buchanan', 'FW'],
    [19, 'Alphonso Davies', 'FW'],
    [9, 'Jonathan David', 'FW'],
  ], [[14, 'Jacob Shaffelburg', 'FW']]),

  瑞士: L('4-2-3-1', [
    [1, 'Yann Sommer', 'GK'],
    [21, 'Manuel Akanji', 'DF'],
    [13, 'Ricardo Rodríguez', 'DF'],
    [5, 'Nico Elvedi', 'DF'],
    [3, 'Silvan Widmer', 'DF'],
    [10, 'Granit Xhaka', 'MF'],
    [8, 'Ruben Vargas', 'MF'],
    [23, 'Xherdan Shaqiri', 'MF'],
    [15, 'Denis Zakaria', 'MF'],
    [7, 'Breel Embolo', 'FW'],
    [9, 'Dan Ndoye', 'FW'],
  ], [[11, 'Noah Okafor', 'FW']]),

  波黑: L('4-3-3', [
    [1, 'Ibrahim Sehic', 'GK'],
    [5, 'Sead Kolasinac', 'DF'],
    [16, 'Dennis Hadzic', 'DF'],
    [4, 'Stanko Juric', 'DF'],
    [2, 'Adis Jahovic', 'DF'],
    [8, 'Gojko Cimirot', 'MF'],
    [10, 'Miralem Pjanic', 'MF'],
    [19, 'Edin Dzeko', 'MF'],
    [11, 'Ermedin Demirovic', 'FW'],
    [9, 'Luka Menalo', 'FW'],
    [7, 'Benjamin Tahirovic', 'FW'],
  ]),

  卡塔尔: L('4-1-4-1', [
    [22, 'Saad Al Sheeb', 'GK'],
    [2, 'Ro Ro', 'DF'],
    [3, 'Abdelkarim Hassan', 'DF'],
    [14, 'Homam Ahmed', 'DF'],
    [12, 'Bassam Al Rawi', 'DF'],
    [16, 'Boualem Khoukhi', 'MF'],
    [10, 'Hassan Al Haydos', 'MF'],
    [6, 'Abdulaziz Hatem', 'MF'],
    [20, 'Ahmed Alaaeldin', 'MF'],
    [11, 'Akram Afif', 'MF'],
    [19, 'Almoez Ali', 'FW'],
  ]),

  巴西: L('4-2-3-1', [
    [1, 'Alisson', 'GK'],
    [2, 'Danilo', 'DF'],
    [4, 'Marquinhos', 'DF'],
    [3, 'Gabriel Magalhães', 'DF'],
    [6, 'Guilherme Arana', 'DF'],
    [5, 'Bruno Guimarães', 'MF'],
    [8, 'André', 'MF'],
    [10, 'Rodrygo', 'MF'],
    [20, 'Estêvão', 'MF'],
    [7, 'Vinícius Júnior', 'MF'],
    [9, 'Richarlison', 'FW'],
  ], [[11, 'Raphinha', 'FW']]),

  摩洛哥: L('4-3-3', [
    [1, 'Yassine Bounou', 'GK'],
    [2, 'Achraf Hakimi', 'DF'],
    [5, 'Nayef Aguerd', 'DF'],
    [6, 'Romain Saiss', 'DF'],
    [25, 'Noussair Mazraoui', 'DF'],
    [4, 'Sofyan Amrabat', 'MF'],
    [8, 'Azzedine Ounahi', 'MF'],
    [7, 'Bilal El Khannouss', 'MF'],
    [10, 'Brahim Díaz', 'FW'],
    [19, 'Youssef En-Nesyri', 'FW'],
    [16, 'Ez Abde', 'FW'],
  ]),

  苏格兰: L('3-5-2', [
    [1, 'Angus Gunn', 'GK'],
    [15, 'Jack Hendry', 'DF'],
    [26, 'Scott McKenna', 'DF'],
    [6, 'Grant Hanley', 'DF'],
    [2, 'Ross McCrorie', 'MF'],
    [8, 'Callum McGregor', 'MF'],
    [4, 'Scott McTominay', 'MF'],
    [3, 'Andrew Robertson', 'MF'],
    [11, 'Ryan Christie', 'MF'],
    [9, 'Lyndon Dykes', 'FW'],
    [10, 'Che Adams', 'FW'],
  ], [[7, 'John McGinn', 'MF']], '末轮对巴西需抢分'),

  海地: L('5-4-1', [
    [1, 'Johny Placide', 'GK'],
    [4, 'Carlens Arcus', 'DF'],
    [3, 'Jems Geffrard', 'DF'],
    [21, 'Mickael Métellus', 'DF'],
    [6, 'Derrick Etienne', 'DF'],
    [2, 'Martin Experience', 'DF'],
    [8, 'Bryan Alceus', 'MF'],
    [14, 'Derrick Etienne Jr.', 'MF'],
    [10, 'Duckens Nazon', 'MF'],
    [7, 'Zachary Herivaux', 'MF'],
    [9, 'Frantzdy Pierrot', 'FW'],
  ]),

  美国: L('4-3-3', [
    [1, 'Matt Turner', 'GK'],
    [2, 'Sergiño Dest', 'DF'],
    [13, 'Tim Ream', 'DF'],
    [12, 'Miles Robinson', 'DF'],
    [5, 'Antonee Robinson', 'DF'],
    [6, 'Yunus Musah', 'MF'],
    [8, 'Weston McKennie', 'MF'],
    [10, 'Christian Pulisic', 'MF'],
    [7, 'Giovanni Reyna', 'MF'],
    [9, 'Ricardo Pepi', 'FW'],
    [11, 'Folarin Balogun', 'FW'],
  ]),

  澳大利亚: L('4-2-3-1', [
    [1, 'Mathew Ryan', 'GK'],
    [2, 'Fran Karačić', 'DF'],
    [19, 'Harry Souttar', 'DF'],
    [4, 'Kye Rowles', 'DF'],
    [16, 'Aziz Behich', 'DF'],
    [13, 'Aiden O\'Neill', 'MF'],
    [22, 'Riley McGree', 'MF'],
    [10, 'Kusini Yengi', 'MF'],
    [17, 'Keanu Baccus', 'MF'],
    [7, 'Riley McGree', 'MF'],
    [9, 'Mitchell Duke', 'FW'],
  ], [[15, 'Garang Kuol', 'FW']], '末轮对巴拉圭争出线'),

  巴拉圭: L('4-4-2', [
    [1, 'Carlos Coronel', 'GK'],
    [4, 'Omar Alderete', 'DF'],
    [3, 'Juan Fidel Insfrán', 'DF'],
    [2, 'Robert Rojas', 'DF'],
    [13, 'Matías Espinoza', 'DF'],
    [10, 'Miguel Almirón', 'MF'],
    [16, 'Matías Galarza', 'MF'],
    [8, 'Diego Gómez', 'MF'],
    [7, 'Ramón Sosa', 'MF'],
    [9, 'Miguel Almirón', 'FW'],
    [11, 'Adam Bareiro', 'FW'],
  ], [[20, 'Julio Enciso', 'FW']], '末轮对澳大利亚生死战'),

  土耳其: L('4-2-3-1', [
    [1, 'Ugurcan Çakir', 'GK'],
    [18, 'Zeki Celik', 'DF'],
    [3, 'Merih Demiral', 'DF'],
    [4, 'Abdulkerim Bardakci', 'DF'],
    [22, 'Mert Müldür', 'DF'],
    [5, 'Ismail Yuksek', 'MF'],
    [6, 'Orkun Kökçü', 'MF'],
    [10, 'Hakan Çalhanoğlu', 'MF'],
    [7, 'Kerem Aktürkoğlu', 'MF'],
    [9, 'Baris Alper Yilmaz', 'FW'],
    [17, 'Cengiz Under', 'FW'],
  ]),

  德国: L('4-2-3-1', [
    [1, 'Manuel Neuer', 'GK'],
    [6, 'Joshua Kimmich', 'DF'],
    [2, 'Antonio Rüdiger', 'DF'],
    [15, 'Jonathan Tah', 'DF'],
    [3, 'David Raum', 'DF'],
    [8, 'Florian Wirtz', 'MF'],
    [21, 'Pascal Groß', 'MF'],
    [10, 'Jamal Musiala', 'MF'],
    [7, 'Leroy Sané', 'MF'],
    [13, 'Thomas Müller', 'MF'],
    [9, 'Niclas Füllkrug', 'FW'],
  ]),

  科特迪瓦: L('4-3-3', [
    [1, 'Badra Ali Sangare', 'GK'],
    [12, 'Wilfried Singo', 'DF'],
    [21, 'Odilon Kossounou', 'DF'],
    [5, 'Eric Bailly', 'DF'],
    [3, 'Ghislain Konan', 'DF'],
    [4, 'Serge Aurier', 'MF'],
    [8, 'Franck Kessié', 'MF'],
    [19, 'Jean-Philippe Krasso', 'MF'],
    [7, 'Nicolas Pépé', 'FW'],
    [9, 'Sebastien Haller', 'FW'],
    [15, 'Jérémie Boga', 'FW'],
  ]),

  厄瓜多尔: L('4-4-2', [
    [1, 'Hernán Galíndez', 'GK'],
    [4, 'Robert Arboleda', 'DF'],
    [2, 'Felix Torres', 'DF'],
    [3, 'Piero Hincapié', 'DF'],
    [7, 'Pervis Estupiñán', 'DF'],
    [6, 'Moises Caicedo', 'MF'],
    [5, 'José Cifuentes', 'MF'],
    [10, 'Kendry Páez', 'MF'],
    [11, 'Michael Estrada', 'MF'],
    [9, 'Enner Valencia', 'FW'],
    [19, 'Jordy Caicedo', 'FW'],
  ]),

  库拉索: L('5-4-1', [
    [1, 'Eloy Room', 'GK'],
    [2, 'Cuca Martina', 'DF'],
    [4, 'Juriën Gaari', 'DF'],
    [3, 'Sherel Floranus', 'DF'],
    [5, 'Ridgeciano Haps', 'DF'],
    [15, 'Brandley Kuwas', 'DF'],
    [8, 'Leandro Bacuna', 'MF'],
    [10, 'Elson Hooi', 'MF'],
    [6, 'Jarchinio Antonia', 'MF'],
    [11, 'Rangelo Janga', 'MF'],
    [9, 'Gino van Kessel', 'FW'],
  ]),

  荷兰: L('4-3-3', [
    [1, 'Bart Verbruggen', 'GK'],
    [22, 'Denzel Dumfries', 'DF'],
    [4, 'Virgil van Dijk', 'DF'],
    [6, 'Nathan Aké', 'DF'],
    [5, 'Jeremie Frimpong', 'DF'],
    [8, 'Tijjani Reijnders', 'MF'],
    [14, 'Joey Veerman', 'MF'],
    [7, 'Steven Bergwijn', 'MF'],
    [11, 'Cody Gakpo', 'FW'],
    [10, 'Memphis Depay', 'FW'],
    [9, 'Brian Brobbey', 'FW'],
  ]),

  日本: L('4-2-3-1', [
    [23, '大迫敬介', 'GK'],
    [16, '每熊晟矢', 'DF'],
    [4, '板仓滉', 'DF'],
    [22, '富安健洋', 'DF'],
    [2, '山根视来', 'DF'],
    [6, '远藤航', 'MF'],
    [14, '佐野海舟', 'MF'],
    [8, '堂安律', 'MF'],
    [10, '久保建英', 'MF'],
    [20, '南野拓实', 'MF'],
    [18, '上田绮世', 'FW'],
  ], [[7, '三笘薰', 'FW']], '末轮对瑞典争头名'),

  瑞典: L('4-4-2', [
    [1, 'Robin Olsen', 'GK'],
    [2, 'Victor Lindelöf', 'DF'],
    [3, 'Pontus Jansson', 'DF'],
    [6, 'Emil Krafth', 'DF'],
    [18, 'Gabriel Gudmundsson', 'DF'],
    [7, 'Emil Forsberg', 'MF'],
    [8, 'Mattias Svanberg', 'MF'],
    [20, 'Dejan Kulusevski', 'MF'],
    [21, 'Jesper Karlsson', 'MF'],
    [9, 'Viktor Gyökeres', 'FW'],
    [11, 'Alexander Isak', 'FW'],
  ], [[17, 'Anthony Elanga', 'FW']], '末轮对日本，+8 形势关键'),

  突尼斯: L('4-3-3', [
    [16, 'Aymen Dahmen', 'GK'],
    [6, 'Nader Ghandri', 'DF'],
    [4, 'Yassine Meriah', 'DF'],
    [3, 'Ali Maaloul', 'DF'],
    [21, 'Hamza Mathlouthi', 'DF'],
    [14, 'Aissa Laidouni', 'MF'],
    [23, 'Naïm Sliti', 'MF'],
    [10, 'Wahbi Khazri', 'MF'],
    [7, 'Hamza Rafia', 'FW'],
    [9, 'Issam Jebali', 'FW'],
    [25, 'Taha Yassine Khenissi', 'FW'],
  ]),

  埃及: L('4-3-3', [
    [1, 'Mohamed El Shenawy', 'GK'],
    [3, 'Mohamed Hany', 'DF'],
    [6, 'Ahmed Hegazi', 'DF'],
    [15, 'Omar Kamal', 'DF'],
    [13, 'Ahmed Abou El Enein', 'DF'],
    [17, 'Mohamed Elneny', 'MF'],
    [8, 'Emam Ashour', 'MF'],
    [22, 'Mohamed Salah', 'MF'],
    [10, 'Trézéguet', 'FW'],
    [9, 'Omar Marmoush', 'FW'],
    [11, 'Mostafa Mohamed', 'FW'],
  ]),

  伊朗: L('4-1-4-1', [
    [1, 'Alireza Beiranvand', 'GK'],
    [19, 'Hossein Kanani', 'DF'],
    [4, 'Shojae Khalilzadeh', 'DF'],
    [8, 'Morteza Pouraliganji', 'DF'],
    [5, 'Milad Mohammadi', 'DF'],
    [6, 'Saeid Ezatolahi', 'MF'],
    [14, 'Alireza Jahanbakhsh', 'MF'],
    [7, 'Mehdi Taremi', 'MF'],
    [18, 'Samaneh Ghoddos', 'MF'],
    [16, 'Mehdi Ghayedi', 'MF'],
    [9, 'Sardar Azmoun', 'FW'],
  ]),

  比利时: L('3-4-2-1', [
    [1, 'Koen Casteels', 'GK'],
    [5, 'Jan Vertonghen', 'DF'],
    [2, 'Zeno Debast', 'DF'],
    [3, 'Arthur Theate', 'DF'],
    [21, 'Timothy Castagne', 'MF'],
    [8, 'Youri Tielemans', 'MF'],
    [6, 'Amadou Onana', 'MF'],
    [9, 'Loïs Openda', 'MF'],
    [10, 'Kevin De Bruyne', 'MF'],
    [7, 'Jeremy Doku', 'MF'],
    [11, 'Romelu Lukaku', 'FW'],
  ], [[14, 'Charles De Ketelaere', 'MF']], 'G 组末轮争出线'),

  新西兰: L('4-4-2', [
    [1, 'Max Crocombe', 'GK'],
    [2, 'Liberato Cacace', 'DF'],
    [5, 'Michael Boxall', 'DF'],
    [6, 'Nando Pijanka', 'DF'],
    [15, 'Bill Tuiloma', 'DF'],
    [8, 'Marko Stamenic', 'MF'],
    [14, 'Marko Rogan', 'MF'],
    [10, 'Marco Rojas', 'MF'],
    [7, 'Ben Waine', 'MF'],
    [9, 'Chris Wood', 'FW'],
    [11, 'Eli Just', 'FW'],
  ]),

  西班牙: L('4-3-3', [
    [23, 'Unai Simón', 'GK'],
    [2, 'Dani Carvajal', 'DF'],
    [3, 'Robin Le Normand', 'DF'],
    [4, 'Aymeric Laporte', 'DF'],
    [22, 'Marc Cucurella', 'DF'],
    [16, 'Rodri', 'MF'],
    [8, 'Fabián Ruiz', 'MF'],
    [10, 'Dani Olmo', 'MF'],
    [19, 'Lamine Yamal', 'FW'],
    [7, 'Álvaro Morata', 'FW'],
    [9, 'Nico Williams', 'FW'],
  ]),

  乌拉圭: L('4-4-2', [
    [1, 'Sergio Rochet', 'GK'],
    [22, 'José Giménez', 'DF'],
    [2, 'Sebastián Coates', 'DF'],
    [13, 'Matías Viña', 'DF'],
    [4, 'Ronald Araújo', 'DF'],
    [15, 'Federico Valverde', 'MF'],
    [6, 'Rodrigo Bentancur', 'MF'],
    [10, 'Giorgian Arrascaeta', 'MF'],
    [7, 'Facundo Pellistri', 'MF'],
    [9, 'Luis Suárez', 'FW'],
    [11, 'Darwin Núñez', 'FW'],
  ]),

  佛得角: L('4-4-2', [
    [1, 'Vozinha', 'GK'],
    [2, 'Stopira', 'DF'],
    [4, 'Józimar', 'DF'],
    [5, 'Bastos', 'DF'],
    [3, 'Diney', 'DF'],
    [6, 'Ryan Mendes', 'MF'],
    [8, 'Marco Tavares', 'MF'],
    [10, 'Jamiro Monteiro', 'MF'],
    [7, 'Garry Rodrigues', 'MF'],
    [9, 'Júlio Tavares', 'FW'],
    [11, 'Platini', 'FW'],
  ]),

  沙特阿拉伯: L('4-2-3-1', [
    [21, 'Mohammed Al-Owais', 'GK'],
    [12, 'Saud Abdulhamid', 'DF'],
    [17, 'Hassan Tambakti', 'DF'],
    [5, 'Ali Al-Bulayhi', 'DF'],
    [13, 'Hassan Al-Tambakti', 'DF'],
    [7, 'Salman Al-Faraj', 'MF'],
    [23, 'Mohamed Kanno', 'MF'],
    [10, 'Salem Al-Dawsari', 'MF'],
    [8, 'Abdullah Al-Khaibari', 'MF'],
    [11, 'Saleh Al-Shehri', 'FW'],
    [9, 'Firas Al-Buraikan', 'FW'],
  ]),

  法国: L('4-3-3', [
    [1, 'Mike Maignan', 'GK'],
    [5, 'Jules Koundé', 'DF'],
    [4, 'Dayot Upamecano', 'DF'],
    [22, 'Théo Hernandez', 'DF'],
    [2, 'Benjamin Pavard', 'DF'],
    [8, 'Aurélien Tchouaméni', 'MF'],
    [14, 'Adrien Rabiot', 'MF'],
    [7, 'Antoine Griezmann', 'MF'],
    [10, 'Kylian Mbappé', 'FW'],
    [9, 'Olivier Giroud', 'FW'],
    [11, 'Ousmane Dembélé', 'FW'],
  ]),

  挪威: L('4-3-3', [
    [1, 'Bernd Leno', 'GK'],
    [22, 'Marcus Pedersen', 'DF'],
    [15, 'Stefan Strandberg', 'DF'],
    [4, 'Leo Østbø', 'DF'],
    [2, 'Julian Ryerson', 'DF'],
    [8, 'Sander Berge', 'MF'],
    [16, 'Martin Ødegaard', 'MF'],
    [10, 'Fredrik Aursnes', 'MF'],
    [11, 'Alexander Sørloth', 'FW'],
    [9, 'Erling Haaland', 'FW'],
    [18, 'Antonio Nusa', 'FW'],
  ]),

  塞内加尔: L('4-3-3', [
    [16, 'Édouard Mendy', 'GK'],
    [21, 'Joseph Mendy', 'DF'],
    [3, 'Kalidou Koulibaly', 'DF'],
    [4, 'Abdu Diallo', 'DF'],
    [12, 'Abdoulaye Seck', 'DF'],
    [15, 'Krépin Diatta', 'MF'],
    [6, 'Idrissa Gueye', 'MF'],
    [13, 'Pape Matar Sarr', 'MF'],
    [10, 'Sadio Mané', 'FW'],
    [9, 'Boulaye Dia', 'FW'],
    [18, 'Ismaïla Sarr', 'FW'],
  ]),

  伊拉克: L('4-2-3-1', [
    [1, 'Jalal Hassan', 'GK'],
    [2, 'Ali Faez', 'DF'],
    [4, 'Mustafa Nadhim', 'DF'],
    [5, 'Saad Natiq', 'DF'],
    [15, 'Ahmed Ibrahim', 'DF'],
    [14, 'Amir Al-Ammari', 'MF'],
    [8, 'Bashar Resan', 'MF'],
    [10, 'Mohammed Ali Ahmed', 'MF'],
    [7, 'Ayman Hussein', 'MF'],
    [9, 'Aymen Hussein', 'FW'],
    [11, 'Zaid Abdullah', 'FW'],
  ]),

  阿根廷: L('4-3-3', [
    [23, 'Emiliano Martínez', 'GK'],
    [4, 'Gonzalo Montiel', 'DF'],
    [13, 'Cristian Romero', 'DF'],
    [19, 'Nicolás Otamendi', 'DF'],
    [3, 'Nicolás Tagliafico', 'DF'],
    [7, 'Rodrigo De Paul', 'MF'],
    [20, 'Alexis Mac Allister', 'MF'],
    [10, 'Lionel Messi', 'MF'],
    [11, 'Ángel Di María', 'FW'],
    [9, 'Julián Álvarez', 'FW'],
    [22, 'Lautaro Martínez', 'FW'],
  ]),

  奥地利: L('4-2-3-1', [
    [13, 'Patrick Pentz', 'GK'],
    [5, 'Stefan Posch', 'DF'],
    [4, 'David Alaba', 'DF'],
    [2, 'Phillipp Mbabu', 'DF'],
    [8, 'David Alaba', 'DF'],
    [9, 'Marcel Sabitzer', 'MF'],
    [10, 'Florian Grillitsch', 'MF'],
    [20, 'Konrad Laimer', 'MF'],
    [7, 'Marko Arnautović', 'MF'],
    [11, 'Michael Gregoritsch', 'FW'],
    [19, 'Christoph Baumgartner', 'MF'],
  ]),

  阿尔及利亚: L('4-3-3', [
    [16, 'Anthony Mandrea', 'GK'],
    [20, 'Youcef Atal', 'DF'],
    [4, 'Ramy Bensebaini', 'DF'],
    [2, 'Aissa Mandi', 'DF'],
    [15, 'Rayane Aouar', 'DF'],
    [8, 'Ismaël Bennacer', 'MF'],
    [22, 'Ramiz Zerrouki', 'MF'],
    [7, 'Riyad Mahrez', 'MF'],
    [10, 'Youcef Belaïli', 'FW'],
    [9, 'Baghdad Bounedjah', 'FW'],
    [11, 'Riyad Mahrez', 'FW'],
  ], [[14, 'Houssem Aouar', 'MF']], '末轮对奥地利争出线'),

  约旦: L('5-4-1', [
    [1, 'Yazeed Abulaila', 'GK'],
    [2, 'Yazan Al-Naimat', 'DF'],
    [4, 'Salem Al-Ajalin', 'DF'],
    [5, 'Tareq Kathem', 'DF'],
    [3, 'Ibrahim Al-Zawahreh', 'DF'],
    [23, 'Musab Al-Laham', 'DF'],
    [8, 'Rajaei Ayed', 'MF'],
    [6, 'Noor Al-Rawabdeh', 'MF'],
    [10, 'Musa Al-Taamari', 'MF'],
    [9, 'Ali Olwan', 'MF'],
    [11, 'Yazan Al-Naimat', 'FW'],
  ]),

  哥伦比亚: L('4-2-3-1', [
    [1, 'Camilo Vargas', 'GK'],
    [4, 'Dávinson Sánchez', 'DF'],
    [23, 'Yerry Mina', 'DF'],
    [6, 'Deiver Machado', 'DF'],
    [21, 'Jhon Lucumí', 'DF'],
    [5, 'Wilmar Barrios', 'MF'],
    [16, 'Jefferson Lerma', 'MF'],
    [10, 'James Rodríguez', 'MF'],
    [11, 'Luis Díaz', 'MF'],
    [7, 'Jhon Arias', 'MF'],
    [9, 'Luis Sinisterra', 'FW'],
  ]),

  民主刚果: L('4-2-3-1', [
    [1, 'Lionel Mpasi', 'GK'],
    [2, 'Jordan Ikoko', 'DF'],
    [5, 'Marcel Tisserand', 'DF'],
    [3, 'Chancel Mbemba', 'DF'],
    [14, 'Issama Mpeko', 'DF'],
    [8, 'Gael Kakuta', 'MF'],
    [6, 'Edo Kayembe', 'MF'],
    [10, 'Théo Bongonda', 'MF'],
    [17, 'Cédric Bakambu', 'MF'],
    [9, 'Fiston Mayele', 'FW'],
    [11, 'Yoane Wissa', 'FW'],
  ]),

  葡萄牙: L('4-3-3', [
    [22, 'Diogo Costa', 'GK'],
    [2, 'João Cancelo', 'DF'],
    [4, 'Rúben Dias', 'DF'],
    [3, 'Pepe', 'DF'],
    [5, 'Nuno Mendes', 'DF'],
    [8, 'Bruno Fernandes', 'MF'],
    [18, 'Ruben Neves', 'MF'],
    [10, 'Bernardo Silva', 'MF'],
    [7, 'Rafael Leão', 'FW'],
    [9, 'Cristiano Ronaldo', 'FW'],
    [11, 'Diogo Jota', 'FW'],
  ], [[17, 'João Félix', 'FW']]),

  乌兹别克斯坦: L('4-4-2', [
    [1, 'Utkirbek Nigmatov', 'GK'],
    [2, 'Khojimat Erkinov', 'DF'],
    [15, 'Abdulla Abdullaev', 'DF'],
    [3, 'Eldor Shomurodov', 'DF'],
    [19, 'Jaloliddin Masharipov', 'DF'],
    [7, 'Odil Khamroev', 'MF'],
    [8, 'Jasur Narzikulov', 'MF'],
    [10, 'Eldor Shomurodov', 'MF'],
    [9, 'Igor Sergeev', 'MF'],
    [11, 'Abbosbek Fayzullaev', 'FW'],
    [20, 'Otabek Shukurov', 'FW'],
  ]),

  英格兰: L('4-2-3-1', [
    [1, 'Jordan Pickford', 'GK'],
    [2, 'Kyle Walker', 'DF'],
    [5, 'John Stones', 'DF'],
    [6, 'Marc Guéhi', 'DF'],
    [3, 'Luke Shaw', 'DF'],
    [4, 'Declan Rice', 'MF'],
    [8, 'Jude Bellingham', 'MF'],
    [10, 'Phil Foden', 'MF'],
    [11, 'Bukayo Saka', 'MF'],
    [7, 'Jack Grealish', 'MF'],
    [9, 'Harry Kane', 'FW'],
  ], [[14, 'Anthony Gordon', 'FW']]),

  加纳: L('4-3-3', [
    [1, 'Lawrence Ati-Zigi', 'GK'],
    [2, 'Tariq Lamptey', 'DF'],
    [18, 'Daniel Amartey', 'DF'],
    [21, 'Salisu Abdulai', 'DF'],
    [4, 'Daniel Amartey', 'DF'],
    [5, 'Thomas Partey', 'MF'],
    [8, 'Mohammed Kudus', 'MF'],
    [20, 'Mohammed Kudus', 'MF'],
    [9, 'Jordan Ayew', 'FW'],
    [19, 'Inaki Williams', 'FW'],
    [10, 'Kamaldeen Sulemana', 'FW'],
  ]),

  巴拿马: L('5-4-1', [
    [1, 'Orlando Mosquera', 'GK'],
    [3, 'Harold Cummings', 'DF'],
    [4, 'Fidel Escobar', 'DF'],
    [2, 'Michael Murillo', 'DF'],
    [23, 'Guillermo Marquez', 'DF'],
    [15, 'Eric Davis', 'DF'],
    [8, 'Anibal Godoy', 'MF'],
    [6, 'Adalberto Carrasquilla', 'MF'],
    [10, 'Alberto Quintero', 'MF'],
    [17, 'Jose Fajardo', 'MF'],
    [9, 'Jose Fajardo', 'FW'],
  ]),

  克罗地亚: L('4-3-3', [
    [1, 'Dominik Livakovic', 'GK'],
    [22, 'Josip Juranovic', 'DF'],
    [20, 'Bruno Petkovic', 'DF'],
    [4, 'Josko Gvardiol', 'DF'],
    [3, 'Borna Sosa', 'DF'],
    [10, 'Luka Modric', 'MF'],
    [8, 'Mateo Kovacic', 'MF'],
    [15, 'Pasalic', 'MF'],
    [7, 'Perisic', 'FW'],
    [9, 'Marko Livaja', 'FW'],
    [11, 'Ivan Perisic', 'FW'],
  ], [[16, 'Budimir', 'FW']], '末两轮需全力抢分'),
};

export function getTeamLineup(teamName: string): TeamLineup | undefined {
  return TEAM_LINEUPS[teamName];
}
